# SETUP
baseurl = "/"
DefaultContentLanguage = "en"
publishdir = "public"
canonifyUrls = "true"
disableKinds = ["RSS","taxonomy","taxonomyTerm"] # disable hugo's content that we don't need...

title = "Cured Compliance - curing compliance and making it enjoyable" # page title -> see ./layouts/partials/head.html

googleAnalytics = "G-HLHSCC5JWV" # if needed...

[author]
    name = "Cured Compliance"
    email = "help@curedcompliance.com"

[params]
    description = "Cured Compliance - curing compliance and making it enjoyable" # page description -> see ./layouts/partials/head.html
    images = [] #add images here as "img/name.ext" (points to s./static/img/) to populate the default og and twitter <meta> attributes -> see ./layouts/partials/head.html

# these items will be rendered 1. into a tooltip in the navbar and 2. into the footer - consider that there's limited space when adding more items -> see ./layouts/partials

[[params.social]]
    title = "LinkedIn"
    url = "https://linkedin.com/company/75633596" # add your linkedin profile URL
[[params.social]]
    title = "Facebook"
    url = "https://www.facebook.com/profile.php?id=100085357347917" # add your linkedin profile URL

[sitemap]
  changeFreq = 'always'
  disable = false
  filename = 'sitemap.xml'
  priority = -1