# SETUP
baseurl = "/"
DefaultContentLanguage = "en"
publishdir = "public"
canonifyUrls = "true"
disableKinds = ["RSS","taxonomy","taxonomyTerm"] # disable hugo's content that we don't need...

title = "Cured Compliance - Specialised compliance software for butchers and meat industry professionals." # page title -> see ./layouts/partials/head.html

[author]
    name = "Cured Compliance"
    email = "help@curedcompliance.com"

[params]
    description = "Cured Compliance - Specialised compliance software for butchers and meat industry professionals." # page description -> see ./layouts/partials/head.html
    images = [] #add images here as "img/name.ext" (points to s./static/img/) to populate the default og and twitter <meta> attributes -> see ./layouts/partials/head.html

[[params.social]]
    title = "LinkedIn"
    url = "https://linkedin.com/company/75633596" # add your linkedin profile URL
[[params.social]]
    title = "Facebook"
    url = "https://www.facebook.com/profile.php?id=100085357347917" # add your linkedin profile URL

[sitemap]
  changeFreq = 'always'
  disable = false
  filename = 'sitemap.xml'
  priority = -1

[menus]
  [[menus.main]]
    identifier = 'Features'
    name = 'Features'
    pageRef = '/features'
    weight = 10
  [[menus.main]]
    identifier = "Story"
    name = 'Our Story'
    pageRef = '/About'
    weight = 1
  [[menus.main]]
    identifier = "Resources"
    name = 'Resources'
    pageRef = '/resources'
    weight = 40
  [[menus.main]]
    identifier = "media"
    name = 'Media'
    pageRef = '/media'
    weight = 50